// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dRRaws8KMTaP3P1VBiYS_UtZvoVuTTA',
    appId: '1:64233866167:web:c4773f962dd399a8851e32',
    messagingSenderId: '64233866167',
    projectId: 'drivetrackingsolution',
    authDomain: 'drivetrackingsolution.firebaseapp.com',
    storageBucket: 'drivetrackingsolution.appspot.com',
    measurementId: 'G-GT34QX24RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0zJAeGu4g85_-s5B6xuQ3brTO1ywy28',
    appId: '1:64233866167:android:54a25927e91f7cb5851e32',
    messagingSenderId: '64233866167',
    projectId: 'drivetrackingsolution',
    storageBucket: 'drivetrackingsolution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMr-dnYSrDpzyZO9Uui3DnfR98DK74RaM',
    appId: '1:64233866167:ios:3cd3648d552165ec851e32',
    messagingSenderId: '64233866167',
    projectId: 'drivetrackingsolution',
    storageBucket: 'drivetrackingsolution.appspot.com',
    iosClientId: '64233866167-eak5rtjvq8n7gvrthjnfhtmfanqqvi75.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveTrackingSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMr-dnYSrDpzyZO9Uui3DnfR98DK74RaM',
    appId: '1:64233866167:ios:3cd3648d552165ec851e32',
    messagingSenderId: '64233866167',
    projectId: 'drivetrackingsolution',
    storageBucket: 'drivetrackingsolution.appspot.com',
    iosClientId: '64233866167-eak5rtjvq8n7gvrthjnfhtmfanqqvi75.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveTrackingSolutions',
  );
}
